const ONE_DAY_SECONDS = "86400";
const { CEP_CACHE_MAX_AGE_SECONDS = ONE_DAY_SECONDS } = process.env;
const CEP_LENGTH = 8;
const CEP_ZERO = "00000000";

export { CEP_CACHE_MAX_AGE_SECONDS, CEP_LENGTH, CEP_ZERO };
